networks:
  cdc_network:
    driver: bridge

volumes:
  postgres_data:
  clickhouse_data:
  clickhouse_logs:
  grafana_data:

services:
  postgres:
    image: postgres:18
    container_name: postgres_oltp
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${PSQL_USER}"
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: "${PSQL_DB}"
    ports:
      - "127.0.0.1:5432:5432"
      - "172.29.172.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./data:/data
    networks:
      - cdc_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${PSQL_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:26.1
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "127.0.0.1:8123:8123"   # HTTP interface (used by Python consumer, dbt, Grafana)
      - "127.0.0.1:9000:9000"   # Native TCP interface
      - "172.29.172.1:8123:8123"   # HTTP interface (used by Python consumer, dbt, Grafana)
      - "172.29.172.1:9000:9000"   # Native TCP interface
    environment:
      CLICKHOUSE_USER: "${CH_USER}"
      CLICKHOUSE_PASSWORD: "${CH_PASSWORD}"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - cdc_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:12.1.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
      - "172.29.172.1:3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource   # Official ClickHouse plugin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning   # Auto-provision datasources & dashboards
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - cdc_network
